name: venv
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.10
  - pip
  - torchvision
  - cudatoolkit
  - pytorch
  - pip:
    - imutils
    - icrawler
    - scikit-learn==0.24.1
    - tqdm
    - pandas
    - pillow
    - Django
    - django-cors-headers
    - django-cleanup
    - django-environ
    - djangorestframework
    - dj_database_url
    - gunicorn
    - whitenoise
    - opencv-python
    - albumentations
    - joblib
    - numpy
    - nltk
