version = 1

exclude_patterns = ["asl-api/static/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 99
  skip_doc_coverage = ["module","magic", "init", "class", "nonpublic"]
