version = 1

exclude_patterns = ["asl-api/static/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ['nodejs']
  plugins = ["react"]
  skip_doc_coverage = ["module","magic", "init", "class", "nonpublic"]


[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 99
  skip_doc_coverage = ["module","magic", "init", "class", "nonpublic"]


[[transformers]]
    name = "prettier"
    enabled = true
