# Generated by Django 3.2.3 on 2021-06-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPractise',
            new_name='PractiseAnswer',
        ),
    ]
