# Generated by Django 3.2.3 on 2021-06-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_gesture_practisequestion_userpractise'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='PractiseQuestion',
            new_name='PracticeQuestion',
        ),
        migrations.DeleteModel(
            name='UserPractise',
        ),
        migrations.AddField(
            model_name='userpractice',
            name='Practice_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.practicequestion'),
        ),
    ]
