# Generated by Django 3.2.3 on 2021-07-04 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_quizchoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PractiseAnswer',
            new_name='PractiseAttempt',
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practise_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.quizchoice')),
            ],
        ),
    ]
