# Generated by Django 3.2.3 on 2021-07-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20210704_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='practise_question',
            new_name='quiz',
        ),
    ]
