# Generated by Django 3.2.3 on 2021-06-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20210607_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpractice',
            old_name='Practice_question',
            new_name='practice_question',
        ),
    ]
