# Generated by Django 3.2.3 on 2021-06-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_rename_practice_question_userpractice_practice_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PracticeQuestion',
            new_name='PractiseQuestion',
        ),
        migrations.RenameModel(
            old_name='UserPractice',
            new_name='UserPractise',
        ),
        migrations.RenameField(
            model_name='userpractise',
            old_name='practice_question',
            new_name='practise_question',
        ),
    ]
