# Generated by Django 3.2.3 on 2021-07-04 13:06

import django.core.validators
from django.db import migrations, models
import engine.validators


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20210704_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizchoice',
            name='images',
            field=models.ManyToManyField(blank=True, to='engine.Gesture'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='response',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quizchoice',
            name='choice',
            field=models.CharField(max_length=200, validators=[engine.validators.validate_choices], verbose_name='QuizChoice'),
        ),
        migrations.AlterField(
            model_name='quizchoice',
            name='position',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
    ]
