# Generated by Django 3.2.3 on 2021-07-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20210704_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizchoice',
            name='images',
        ),
    ]
