# Generated by Django 3.2.3 on 2021-07-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_remove_quizchoice_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='images',
            field=models.ManyToManyField(blank=True, to='engine.Gesture'),
        ),
    ]
