# Generated by Django 3.2.3 on 2021-07-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_auto_20210705_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizchoice',
            name='images',
        ),
    ]
